package com.enterprise.platform.events;

public enum OrganizationEventType {

    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_DELETED,
    ORGANIZATION_MEMBER_ADDED,
    ORGANIZATION_MEMBER_REMOVED,
    ORGANIZATION_MEMBER_ROLE_CHANGED

}
