apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enterprise-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - infrastructure/postgres.yaml
  - infrastructure/kafka.yaml
  - infrastructure/redis.yaml
  - services/config-server.yaml
  - services/discovery-server.yaml
  - services/api-gateway.yaml
  - services/auth-service.yaml
  - services/user-service.yaml
  - services/organization-service.yaml
  - services/project-service.yaml
  - services/task-service.yaml
  - services/sprint-service.yaml
  - services/resource-service.yaml
  - services/analytics-service.yaml
  - services/notification-service.yaml
  - services/audit-service.yaml
  - frontend/frontend.yaml
  - ingress.yaml
