apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: enterprise-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: auth_db
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: enterprise-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
