package com.enterprise.platform.auth.constant.enums;

public enum PermissionType {

    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_VIEW,

    PROFILE_VIEW,
    PROFILE_UPDATE,

    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    DESIGNATION_CREATE,
    DESIGNATION_UPDATE,
    DESIGNATION_DELETE,

    USER_ASSIGN_MANAGER,

    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,

    TASK_CREATE,
    TASK_ASSIGN,
    TASK_UPDATE,

    KPI_VIEW,
    REPORT_VIEW
}
