spring.application.name=discovery-server

server.port=8761

# =========================================
# CONFIG SERVER
# =========================================

spring.config.import=optional:configserver:http://config-server:8888

# =========================================
# EUREKA
# =========================================

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# =========================================
# ACTUATOR
# =========================================

management.endpoints.web.exposure.include=*